//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int ID { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<bool> OdenmeDurumu { get; set; }
        public Nullable<int> OdemeTipiID { get; set; }
        public string Aciklama { get; set; }
    
        public virtual OdemeTipi OdemeTipi { get; set; }
    }
}
