//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTablo
    {
        public int ID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string TabloAdi { get; set; }
        public string Yapilanİslem { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string Aciklama { get; set; }
    }
}
