//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeyselEntities : DbContext
    {
        public VeyselEntities()
            : base("name=VeyselEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Boyut> Boyut { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<KategoriUrun> KategoriUrun { get; set; }
        public virtual DbSet<ListeFiyat> ListeFiyat { get; set; }
        public virtual DbSet<LogTablo> LogTablo { get; set; }
        public virtual DbSet<Materyal> Materyal { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<OdemeTipi> OdemeTipi { get; set; }
        public virtual DbSet<SatinAlma> SatinAlma { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<StokTablo> StokTablo { get; set; }
        public virtual DbSet<Tedarikci> Tedarikci { get; set; }
        public virtual DbSet<testTable> testTable { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
    }
}
