//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlma
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public int TedarikciID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public Nullable<double> ToplamFiyat { get; set; }
        public Nullable<int> KDVOranı { get; set; }
        public Nullable<System.DateTime> SatınAlmaTarihi { get; set; }
    
        public virtual Tedarikci Tedarikci { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
