//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<double> ListeSatisFiyat { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public Nullable<double> ToplamSatisFiyat { get; set; }
        public Nullable<int> KDV { get; set; }
        public string Aciklama { get; set; }
        public string SiparisTarihi { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
