//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokTablo
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> AlarmSeviyesi { get; set; }
        public Nullable<bool> StokAlarm { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
