//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.KategoriUrun = new HashSet<KategoriUrun>();
            this.ListeFiyat = new HashSet<ListeFiyat>();
            this.SatinAlma = new HashSet<SatinAlma>();
            this.Siparis = new HashSet<Siparis>();
            this.StokTablo = new HashSet<StokTablo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MateryalID { get; set; }
        public Nullable<int> BoyutID { get; set; }
        public string UrunAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Boyut Boyut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KategoriUrun> KategoriUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListeFiyat> ListeFiyat { get; set; }
        public virtual Materyal Materyal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatinAlma> SatinAlma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokTablo> StokTablo { get; set; }
    }
}
